version: '2'
services:
  mongodb:
      image: mongo:3.2
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/var/store/mongodb/db:/data/db"
      network_mode: "host"
      restart: always

  redis:
      image: redis
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/var/store/redis/:/data"
      restart: always

  lolo:
      build: ./dockerfiles/asterisk/
      volumes:
        - "./config/etc/asterisk/:/etc/asterisk/"
      network_mode: "host"      
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
      restart: always

  mysql:
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=1234
        - MYSQL_DATABASE=cdr
      network_mode: "host"
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/var/store/mysql/lib/mysql:/var/lib/mysql"
        - "./misc/cdr/:/docker-entrypoint-initdb.d"
      restart: always

  configserver:
      build: ./dockerfiles/configserver
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
      restart: always

  logcallserver:
      build: ./dockerfiles/logcallserver
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
      restart: always